on:
  push:
    branches:
      - main

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Prepare build
        run: chmod +x ./build.sh

      - name: Create archives
        run: ./build.sh create-archives

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./archives/**
          automatic_release_tag: "latest"
