on:
  push:
    branches:
      - main

jobs:

  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      #      - name: Prepare build
      #        run: chmod +x ./build.sh

      - name: Create archives
        run: ./build.ps create-archives

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./archives/**
          automatic_release_tag: "latest"
